# Generated by Django 4.2.6 on 2023-11-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_feedback_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='size',
            new_name='clothes_size',
        ),
        migrations.AddField(
            model_name='feedback',
            name='foot_size',
            field=models.IntegerField(default=1, verbose_name='Размер ноги'),
            preserve_default=False,
        ),
    ]
